spring.application.name=CinematicMultiverse
spring.jpa.hibernate.ddl-auto=create-drop
spring.profiles.active=dev, pgsql

springdoc.api-docs.path=/api-docs

spring.docker.compose.enable=true
spring.docker.compose.file=docker-compose.yml

#Seguridad

jwt.secret=EsUnSecretoDeTuMiradaYLaMiaUnPresentimiento
jwt.duration=1
jwt.refresh.duration=2

# In minutes
activation.duration=5

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hernandez.meraf23@triana.salesianos.edu
spring.mail.password=fmnh oxeg ipae palj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


