spring.application.name=CinematicMultiverse
spring.jpa.hibernate.ddl-auto=create-drop
spring.profiles.active=dev, pgsql

springdoc.api-docs.path=/api-docs

spring.docker.compose.enable=true
spring.docker.compose.file=docker-compose.yml

#Seguridad

jwt.secret=EsUnSecretoDeTuMiradaYLaMiaUnPresentimiento
jwt.duration=1
jwt.refresh.duration=2

# In minutes
activation.duration=5

# Sendgrid
#sendgrid.api.key=KD89TYJTBBSYFHADEB8ZMJQL

# Resend
resend.api.key=re_fhC6F4W1_FRxwPpNWdmtE3Ku9pHCnFdPD


